# Generated by Django 5.2.3 on 2025-06-27 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the problem', max_length=255, unique=True)),
                ('statement', models.TextField(help_text='Full problem description')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='Difficulty level of the problem', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this problem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problems',
                'verbose_name_plural': 'Problems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='The submission code.')),
                ('language', models.CharField(help_text="Programming language used (e.g., 'Python', 'C++', 'Java').", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('finished', 'Finished')], default='pending', help_text='Current status of the submission evaluation.', max_length=20)),
                ('final_verdict', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('pending', 'Pending Evaluation')], default='pending', help_text='Final verdict of the submission.', max_length=50)),
                ('passed_test_cases', models.IntegerField(blank=True, default=0, help_text='Number of test cases passed.', null=True)),
                ('total_test_cases', models.IntegerField(blank=True, default=0, help_text='Total number of test cases for the problem.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if compilation or runtime error occurred.', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds.', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text='Memory used in KB or MB.', null=True)),
                ('problem', models.ForeignKey(help_text='The problem this submission is for.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(help_text='The user who made this submission', on_delete=django.db.models.deletion.CASCADE, related_name='submission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input for the test case.')),
                ('expected_output', models.TextField(help_text='Expected output for the testcase')),
                ('is_hidden', models.BooleanField(default=True, help_text='If True this test case is hidden from users.')),
                ('order', models.IntegerField(default=0, help_text='Order of the test case.')),
                ('problem', models.ForeignKey(help_text='The problem this testcase belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'ordering': ['order'],
                'unique_together': {('problem', 'order')},
            },
        ),
    ]
