# Generated by Django 5.2.3 on 2025-06-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
