# Generated by Django 5.2.3 on 2025-07-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='Flag to determine if a problem setter is authorized to create problems'),
        ),
    ]
