version: '3.8'
services:
  web:
    build: .
    container_name: online_judge_web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # For judge containers
      - /tmp/oj_submissions:/tmp/oj_submissions
    restart: always

  redis:
    image: redis:7-alpine
    container_name: online_judge_redis
    ports:
      - "6379:6379"
    restart: always