# Generated by Django 5.2.3 on 2025-06-27 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0002_delete_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='The submitted code.')),
                ('language', models.CharField(help_text="Programming language used (e.g., 'python', 'cpp', 'java').", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('finished', 'Finished')], default='pending', help_text='Current status of the submission evaluation.', max_length=20)),
                ('final_verdict', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('pending', 'Pending Evaluation')], default='pending', help_text='Final verdict of the submission.', max_length=50)),
                ('passed_test_cases', models.IntegerField(blank=True, default=0, help_text='Number of test cases passed.', null=True)),
                ('total_test_cases', models.IntegerField(blank=True, default=0, help_text='Total number of test cases for the problem.', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if compilation or runtime error occurred.', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds.', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text='Memory used in KB or MB.', null=True)),
                ('problem', models.ForeignKey(help_text='The problem this submission is for.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(help_text='The user who made this submission.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
