# Generated by Django 5.2.3 on 2025-07-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contestsubmission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='final_verdict',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('judging_error', 'Judging Error')], default='pending', help_text='The final verdict of the submission after evaluation', max_length=25),
        ),
    ]
