# Generated by Django 5.2.3 on 2025-07-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contestsubmission_final_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestsubmission',
            name='final_verdict',
        ),
        migrations.RemoveField(
            model_name='contestsubmission',
            name='language',
        ),
    ]
