# Generated by Django 5.2.3 on 2025-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_remove_contestsubmission_final_verdict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='language',
            field=models.CharField(default='python', help_text='Programming language used for the submission', max_length=50),
        ),
    ]
