# Generated by Django 5.2.3 on 2025-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_contestsubmission_final_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='execution_time',
            field=models.FloatField(default=0.0, help_text='Execution time in seconds'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='memory_used',
            field=models.FloatField(default=0.0, help_text='Memory used in MB'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='final_verdict',
            field=models.CharField(choices=[('pending', 'Pending Evaluation'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('judging_error', 'Judging Error')], default='pending', help_text='The final verdict of the submission after evaluation', max_length=25),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('finished', 'Finished')], default='pending', help_text='Current state of the submission evaluation (e.g., pending, processing, finished)', max_length=25),
        ),
    ]
