# Generated by Django 5.2.3 on 2025-07-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_contestsubmission_execution_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='final_verdict',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error'), ('pending', 'Pending Evaluation'), ('judging_error', 'Judging Error')], default='pending', help_text='Final verdict of the submission.', max_length=50),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('finished', 'Finished')], default='pending', help_text='Current status of the submission evaluation.', max_length=20),
        ),
    ]
