# Generated by Django 5.2.3 on 2025-07-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_fix_status_values'),
        ('contests', '0010_alter_contestsubmission_final_verdict'),
    ]

    operations = [
    ]
