# Generated by Django 5.2.4 on 2025-07-14 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_merge_20250712_2335'),
        ('problems', '0002_delete_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['status'], name='contests_co_status_6c305a_idx'),
        ),
    ]
